version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/squidooo
    stdin_open: true
    tty: true
    ports:
      - '4000:4000'
      - '8080:8080'
